### ISSUE TITLE
Hola Universo

### ISSUE THREAD

**Issue by LuciaB16** [SanLopezIgle/jugandoConPullRequest#1]
Propongo cambio a "Hola Universo"

**Comment by SanLopezIgle** [comment]
no me parece bien

**Comment by LuciaB16** [comment]
Me da igual lo que te parezca

**Comment by SanLopezIgle** [comment]
soy el lider, yo decido bobolona

**Comment by LuciaB16** [comment]
Nadie te dio ese privilegio, venga dale pesada

**Comment by SanLopezIgle** [comment]
bueno venga
